/* Hottest 68000 opcode handlers, placed in SRAM (.time_critical.*) so
   they do not compete with Kickstart and chip RAM for the XIP cache; the
   other handlers stay in flash. Generated by tooling/hotops.py from PC
   samples on the board (5 sessions). Included from m68kops.h after the
   handler prototypes when OMEGA_HOT_OPCODES_IN_RAM is on. */
#ifndef M68KHOT__HEADER
#define M68KHOT__HEADER
#include "pico.h"

void __not_in_flash_func(m68k_op_add_16_er_d)(void);
void __not_in_flash_func(m68k_op_add_32_er_d)(void);
void __not_in_flash_func(m68k_op_addi_16_d)(void);
void __not_in_flash_func(m68k_op_addq_16_d)(void);
void __not_in_flash_func(m68k_op_addq_32_a)(void);
void __not_in_flash_func(m68k_op_and_16_er_d)(void);
void __not_in_flash_func(m68k_op_and_16_re_di)(void);
void __not_in_flash_func(m68k_op_andi_16_al)(void);
void __not_in_flash_func(m68k_op_andi_32_d)(void);
void __not_in_flash_func(m68k_op_andi_8_d)(void);
void __not_in_flash_func(m68k_op_andi_8_di)(void);
void __not_in_flash_func(m68k_op_beq_16)(void);
void __not_in_flash_func(m68k_op_beq_8)(void);
void __not_in_flash_func(m68k_op_bgt_8)(void);
void __not_in_flash_func(m68k_op_bne_8)(void);
void __not_in_flash_func(m68k_op_bra_16)(void);
void __not_in_flash_func(m68k_op_bsr_16)(void);
void __not_in_flash_func(m68k_op_btst_32_s_d)(void);
void __not_in_flash_func(m68k_op_btst_8_s_al)(void);
void __not_in_flash_func(m68k_op_btst_8_s_di)(void);
void __not_in_flash_func(m68k_op_clr_16_d)(void);
void __not_in_flash_func(m68k_op_clr_32_di)(void);
void __not_in_flash_func(m68k_op_clr_8_di)(void);
void __not_in_flash_func(m68k_op_cmp_16_d)(void);
void __not_in_flash_func(m68k_op_cmp_16_di)(void);
void __not_in_flash_func(m68k_op_cmp_16_pi)(void);
void __not_in_flash_func(m68k_op_cmp_32_ai)(void);
void __not_in_flash_func(m68k_op_cmp_32_d)(void);
void __not_in_flash_func(m68k_op_cmpa_32_a)(void);
void __not_in_flash_func(m68k_op_cmpi_16_pi)(void);
void __not_in_flash_func(m68k_op_cmpi_8_d)(void);
void __not_in_flash_func(m68k_op_dbeq_16)(void);
void __not_in_flash_func(m68k_op_dbf_16)(void);
void __not_in_flash_func(m68k_op_eor_32_d)(void);
void __not_in_flash_func(m68k_op_exg_32_dd)(void);
void __not_in_flash_func(m68k_op_jsr_32_di)(void);
void __not_in_flash_func(m68k_op_lea_32_al)(void);
void __not_in_flash_func(m68k_op_lea_32_di)(void);
void __not_in_flash_func(m68k_op_lsl_16_s)(void);
void __not_in_flash_func(m68k_op_lsr_32_s)(void);
void __not_in_flash_func(m68k_op_move_16_al_i)(void);
void __not_in_flash_func(m68k_op_move_16_d_al)(void);
void __not_in_flash_func(m68k_op_move_16_d_d)(void);
void __not_in_flash_func(m68k_op_move_16_d_i)(void);
void __not_in_flash_func(m68k_op_move_16_d_pi)(void);
void __not_in_flash_func(m68k_op_move_16_di_d)(void);
void __not_in_flash_func(m68k_op_move_32_d_di)(void);
void __not_in_flash_func(m68k_op_move_32_d_pi)(void);
void __not_in_flash_func(m68k_op_move_32_di_a)(void);
void __not_in_flash_func(m68k_op_move_32_di_d)(void);
void __not_in_flash_func(m68k_op_move_32_pi_d)(void);
void __not_in_flash_func(m68k_op_move_8_d_al)(void);
void __not_in_flash_func(m68k_op_move_8_d_di)(void);
void __not_in_flash_func(m68k_op_move_8_d_pi)(void);
void __not_in_flash_func(m68k_op_move_8_pd_pd)(void);
void __not_in_flash_func(m68k_op_movea_32_di)(void);
void __not_in_flash_func(m68k_op_movem_16_er_ix)(void);
void __not_in_flash_func(m68k_op_movem_16_re_al)(void);
void __not_in_flash_func(m68k_op_movem_32_er_di)(void);
void __not_in_flash_func(m68k_op_movem_32_er_pi)(void);
void __not_in_flash_func(m68k_op_movem_32_re_ai)(void);
void __not_in_flash_func(m68k_op_movem_32_re_pd)(void);
void __not_in_flash_func(m68k_op_moveq_32)(void);
void __not_in_flash_func(m68k_op_muls_16_d)(void);
void __not_in_flash_func(m68k_op_or_16_er_d)(void);
void __not_in_flash_func(m68k_op_ori_16_tos)(void);
void __not_in_flash_func(m68k_op_ori_8_di)(void);
void __not_in_flash_func(m68k_op_pea_32_di)(void);
void __not_in_flash_func(m68k_op_rte_32)(void);
void __not_in_flash_func(m68k_op_rts_32)(void);
void __not_in_flash_func(m68k_op_sub_16_er_d)(void);
void __not_in_flash_func(m68k_op_sub_32_er_di)(void);
void __not_in_flash_func(m68k_op_subq_16_d)(void);
void __not_in_flash_func(m68k_op_subq_8_di)(void);
void __not_in_flash_func(m68k_op_swap_32)(void);

#endif /* M68KHOT__HEADER */
