// DVI/HDMI scanout through the RP2350 HSTX peripheral (WeAct GPIO12..19).
//
// HSTX TMDS-encodes RGB888 pixels in hardware. Two ping-pong DMA channels
// feed it one scanline at a time. The double-buffered SRAM frames hold one
// byte per pixel: Amiga colour register numbers / HAM codes (indexed frames,
// see dvi_indexed_frame_t) or RGB332 (boot pattern and the ARGB paths). The
// per-line DMA interrupt on core 1 expands each image row once into RGB888
// and sends it on both of its lines. Buffers change only at a DVI frame
// boundary.

#include "dvi_display.h"
#include "board_config.h"
#include "Host.h"
#include "../omega/VideoStandard.h"

#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/resets.h"
#include "hardware/structs/busctrl.h"
#include "hardware/structs/hstx_ctrl.h"
#include "hardware/structs/hstx_fifo.h"
#include "hardware/structs/timer.h"
#include "hardware/sync.h"
#include "pico/multicore.h"
#include "pico/stdlib.h"

#include <stdio.h>
#include <string.h>

#if OMEGA_VIDEO_STANDARD == OMEGA_VIDEO_PAL
// CEA 720x576p50: 27 MHz pixel clock, 864x625 total pixels.
#define MODE_H_FRONT_PORCH 12u
#define MODE_H_SYNC_WIDTH  64u
#define MODE_H_BACK_PORCH  68u
#define MODE_V_FRONT_PORCH 5u
#define MODE_V_SYNC_WIDTH  5u
#define MODE_V_BACK_PORCH  39u
#define MODE_BIT_CLK_KHZ   270000u
#define DVI_ACTIVE_WIDTH   720u
#define DVI_MODE_NAME      "720x576p50"
#define SOURCE_HEIGHT      288u
// PAL screens such as Workbench use 256 lines; showing only 200 cut off the
// lower edge of windows.
#define AMIGA_SOURCE_HEIGHT 256u
#else
// NTSC builds run clk_sys at 252 MHz, which is exactly VGA 640x480p60
// (25.2 MHz pixels, 252 Mbit/s). A 720x480p60 mode would need 270 MHz; at
// 252 MHz it was a non-standard ~55.9 Hz mode that capture devices locked onto
// unreliably. 640 active pixels also match the Amiga image without borders.
#define MODE_H_FRONT_PORCH 16u
#define MODE_H_SYNC_WIDTH  96u
#define MODE_H_BACK_PORCH  48u
#define MODE_V_FRONT_PORCH 10u
#define MODE_V_SYNC_WIDTH  2u
#define MODE_V_BACK_PORCH  33u
#define MODE_BIT_CLK_KHZ   252000u
#define DVI_ACTIVE_WIDTH   640u
#define DVI_MODE_NAME      "640x480p60"
#define SOURCE_HEIGHT      240u
// Use every row of the 480-line mode: overscan screens (e.g. xsysinfo) run
// to the end of the NTSC frame, beyond 200 lines.
#define AMIGA_SOURCE_HEIGHT 240u
#endif
// Each stored row is sent on two consecutive lines.
#define MODE_V_ACTIVE_LINES (SOURCE_HEIGHT * 2u)

#define AMIGA_SOURCE_WIDTH 640u
#define DVI_IMAGE_X0 ((DVI_ACTIVE_WIDTH - AMIGA_SOURCE_WIDTH) / 2u)
#define DVI_IMAGE_Y0 ((SOURCE_HEIGHT - AMIGA_SOURCE_HEIGHT) / 2u)

// The image frames live in SRAM: the emulator saturates the shared QMI bus,
// and PSRAM line fetches used to miss the scanline deadline. Only the
// 640-wide image is stored; the borders are generated by HSTX commands.
#define DVI_FRAME_W AMIGA_SOURCE_WIDTH
#define DVI_FRAME_H AMIGA_SOURCE_HEIGHT
#define DVI_FRAME_BYTES (DVI_FRAME_W * DVI_FRAME_H)
static uint8_t sram_frames[2][DVI_FRAME_BYTES] __attribute__((aligned(4)));

static uint8_t *source_frames[2];
static bool source_frame_has_emulator[2];
// Indexed frames carry colour numbers plus this record; the others RGB332.
static bool frame_indexed[2];
// The records live in PSRAM (cached alias), which frees ~9.6 KB of SRAM and
// lets the limits grow (RemGame filled the former 448-entry palette log).
// Core 1 writes them and its scanout interrupt reads them, both through the
// one shared XIP cache, so they stay coherent. They are small and read
// sequentially, so scanout mostly hits the cache.
#define frame_records ((dvi_indexed_frame_t *)(BOARD_PSRAM_BASE + \
                                              BOARD_MAP_DVI_RECORDS_OFFSET))
_Static_assert(2u * sizeof(dvi_indexed_frame_t) <= BOARD_MAP_DVI_RECORDS_SIZE,
               "frame records overrun their PSRAM area");
// Frame handshake, one atomic word: bit 0 is the displayed buffer, bit 1 set
// means the other buffer holds a finished frame waiting for the next DVI
// frame boundary (the scanout interrupt swaps at line 0). A finished frame
// is never taken back: renderers claim the back buffer only when nothing is
// pending (core 1 waits briefly for the swap, the ARGB path drops a frame).
#define FRAME_PENDING 2u
static volatile uint32_t frame_state;
// Emulator frames actually shown (swapped in at line 0); read over SWD to
// measure the display update rate.
volatile uint32_t dvi_frames_shown;

// Everything core 1 calls from its thread loop runs from RAM: a flash (XIP)
// fetch can stall behind core 0's PSRAM traffic long enough to delay the
// per-line DMA interrupt past its deadline, which stops scanout for good.
bool __not_in_flash_func(dvi_display_frame_pending)(void) {
    return (__atomic_load_n(&frame_state, __ATOMIC_ACQUIRE) &
            FRAME_PENDING) != 0;
}

// Claims the buffer that is not displayed. Callers first make sure no frame
// is pending, so this never discards a finished frame.
static int __not_in_flash_func(dvi_claim_back_buffer)(void) {
    const uint32_t old = __atomic_fetch_and(&frame_state, ~FRAME_PENDING,
                                            __ATOMIC_ACQ_REL);
    return (int)(old & 1u) ^ 1;
}
static uint64_t boot_pattern_until_us;
// Boot pattern end as a raw 32-bit timer value, for the flash-free check.
static volatile uint32_t boot_pattern_until_lo;
static volatile bool boot_pattern_armed;

static inline bool __not_in_flash_func(boot_pattern_showing)(void) {
    return !boot_pattern_armed ||
           (int32_t)(timer_hw->timerawl - boot_pattern_until_lo) < 0;
}
// Border colour (COLOR00, RGB888) of each frame, for the lines above and
// below the image. Like a real Amiga, the areas around the image show the
// border colour rather than black; indexed rows use their own COLOR00.
static uint32_t frame_border[2];

// 0x0RGB -> RGB888 (each nibble doubled: 0xF -> 0xFF).
static inline uint32_t ocs_rgb888(uint32_t c) {
    return ((c & 0xf00u) << 8 | (c & 0xf0u) << 4 | (c & 0xfu)) * 0x11u;
}
// RGB332 -> RGB888, full range.
static uint32_t rgb332_rgb888[256];

static void dvi_init_rgb332_table(void) {
    for (uint i = 0; i < 256u; ++i) {
        const uint r = (i >> 5) & 7u, g = (i >> 2) & 7u, b = i & 3u;
        rgb332_rgb888[i] = (r * 255u + 3u) / 7u << 16 |
                           (g * 255u + 3u) / 7u << 8 | b * 85u;
    }
}

static inline uint32_t argb_rgb888(uint32_t argb) {
    return argb & 0xffffffu;
}

// Returns the first pixel of image row y (0..AMIGA_SOURCE_HEIGHT-1).
static inline uint8_t *dvi_image_row(uint8_t *frame, uint y) {
    return frame + y * DVI_FRAME_W;
}

static bool dvi_begin_submit(int *target_out, uint8_t **dst_out) {
    // Keep the diagnostic pattern visible long enough to distinguish DVI
    // bring-up from emulator video on a monitor or capture device.
    if (time_us_64() < boot_pattern_until_us)
        return false;

    // Never overwrite a finished frame that has not been shown yet: drop
    // this one instead (the ARGB paths submit whole frames at vblank).
    if (dvi_display_frame_pending())
        return false;
    int target = dvi_claim_back_buffer();
    uint8_t *dst = source_frames[target];
    frame_indexed[target] = false;
    if (!source_frame_has_emulator[target]) {
        memset(dst, 0, DVI_FRAME_BYTES);
        source_frame_has_emulator[target] = true;
    }
    *target_out = target;
    *dst_out = dst;
    return true;
}

static void __not_in_flash_func(dvi_publish_frame)(int target) {
    // Only the claimed back buffer is ever published; core 1 cannot switch
    // buffers until the pending bit is set.
    (void)target;
    __atomic_fetch_or(&frame_state, FRAME_PENDING, __ATOMIC_RELEASE);
}

static int direct_target = -1;

uint32_t dvi_display_bit_clock_khz(void) {
    return MODE_BIT_CLK_KHZ;
}

int __not_in_flash_func(dvi_display_direct_height)(void) {
    return AMIGA_SOURCE_HEIGHT;
}

uint8_t *__not_in_flash_func(dvi_display_direct_acquire)(
    dvi_indexed_frame_t **record) {
    if (boot_pattern_showing())
        return NULL;
    direct_target = dvi_claim_back_buffer();
    source_frame_has_emulator[direct_target] = true;
    *record = &frame_records[direct_target];
    return source_frames[direct_target];
}

void __not_in_flash_func(dvi_display_direct_publish)(uint16_t border) {
    if (direct_target < 0)
        return;
    frame_indexed[direct_target] = true;
    frame_border[direct_target] = ocs_rgb888(border);
    dvi_publish_frame(direct_target);
    direct_target = -1;
}

bool dvi_display_submit_frame(const uint32_t *argb_frame) {
    // Never overwrite a buffer that is displayed or already queued. With two
    // buffers, dropping a late producer frame is safer than tearing scanout.
    int target;
    uint8_t *dst;
    if (!dvi_begin_submit(&target, &dst))
        return false;

    // The presented frame's corner always holds the border colour.
    const uint8_t border_pixel = dvi_rgb332(argb_frame[0]);
    frame_border[target] = argb_rgb888(argb_frame[0]);
    for (uint y = 0; y < AMIGA_SOURCE_HEIGHT; ++y) {
        uint8_t *dst_row = dvi_image_row(dst, y);
        // The presented framebuffer holds SCREEN_H / 2 logical rows.
        if (y >= SCREEN_H / 2u) {
            memset(dst_row, border_pixel, AMIGA_SOURCE_WIDTH);
            continue;
        }
        const uint32_t *src_row = argb_frame + (y * 2u) * SCREEN_W;
        for (uint x = 0; x < AMIGA_SOURCE_WIDTH; ++x)
            dst_row[x] = dvi_rgb332(src_row[x]);
    }

    dvi_publish_frame(target);
    return true;
}

bool dvi_display_submit_raster(const uint32_t *argb_raster,
                               const int16_t *row_min,
                               const int16_t *row_max,
                               uint32_t border,
                               int source_step,
                               int y_offset,
                               int row_rotation) {
    int target;
    uint8_t *dst;
    if (!dvi_begin_submit(&target, &dst))
        return false;

    const uint8_t border_pixel = dvi_rgb332(border);
    frame_border[target] = argb_rgb888(border);
    const int first_source_y = y_offset / 2;
    const int source_rows = HOST_RASTER_H / source_step;

    for (int y = 0; y < AMIGA_SOURCE_HEIGHT; ++y) {
        uint8_t *dst_row = dvi_image_row(dst, (uint)y);
        int source_y = y - first_source_y;
        if (source_y < 0 || source_y >= source_rows) {
            memset(dst_row, border_pixel, AMIGA_SOURCE_WIDTH);
            continue;
        }

        const int raster_row = source_y * source_step;
        const int written_min = row_min[raster_row];
        const unsigned written_width =
            (unsigned)(row_max[raster_row] - written_min);
        if (row_max[raster_row] <= written_min) {
            memset(dst_row, border_pixel, AMIGA_SOURCE_WIDTH);
            continue;
        }
        const uint32_t *src_row = argb_raster + raster_row * SCREEN_W;
        for (int x = 0; x < AMIGA_SOURCE_WIDTH; ++x) {
            int source_x = x + row_rotation;
            if (source_x >= SCREEN_W)
                source_x -= SCREEN_W;
            // Pixels outside this frame's written range are stale; the
            // raster is no longer cleared between frames.
            dst_row[x] = (unsigned)(source_x - written_min) < written_width
                       ? dvi_rgb332(src_row[source_x])
                       : border_pixel;
        }
    }

    dvi_publish_frame(target);
    return true;
}

// ── HSTX scanout ──────────────────────────────────────────────────────────
// TMDS control symbols; lane 0 carries HSYNC (C0) and VSYNC (C1). Both
// supported modes use negative sync polarity, so the idle level is 1.
#define TMDS_CTRL_00 0x354u
#define TMDS_CTRL_01 0x0abu
#define TMDS_CTRL_10 0x154u
#define TMDS_CTRL_11 0x2abu
#define SYNC_V0_H0 (TMDS_CTRL_00 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))
#define SYNC_V0_H1 (TMDS_CTRL_01 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))
#define SYNC_V1_H0 (TMDS_CTRL_10 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))
#define SYNC_V1_H1 (TMDS_CTRL_11 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))

#define HSTX_CMD_RAW_REPEAT  (0x1u << 12)
#define HSTX_CMD_TMDS        (0x2u << 12)
#define HSTX_CMD_TMDS_REPEAT (0x3u << 12)
#define HSTX_CMD_NOP         (0xfu << 12)

// Lines are ordered active first, then the vertical blanking interval.
#define MODE_V_TOTAL_LINES (MODE_V_ACTIVE_LINES + MODE_V_FRONT_PORCH + \
                            MODE_V_SYNC_WIDTH + MODE_V_BACK_PORCH)

#define HBLANK_CMDS(vsync)                                      \
    HSTX_CMD_RAW_REPEAT | MODE_H_FRONT_PORCH, SYNC_V##vsync##_H1, \
    HSTX_CMD_NOP,                                               \
    HSTX_CMD_RAW_REPEAT | MODE_H_SYNC_WIDTH, SYNC_V##vsync##_H0,  \
    HSTX_CMD_NOP,                                               \
    HSTX_CMD_RAW_REPEAT | MODE_H_BACK_PORCH, SYNC_V##vsync##_H1

static uint32_t vblank_line[] = {
    HBLANK_CMDS(1),
    HSTX_CMD_RAW_REPEAT | DVI_ACTIVE_WIDTH, SYNC_V1_H1,
    HSTX_CMD_NOP,
};
static uint32_t vsync_line[] = {
    HBLANK_CMDS(0),
    HSTX_CMD_RAW_REPEAT | DVI_ACTIVE_WIDTH, SYNC_V0_H1,
    HSTX_CMD_NOP,
};
// Active line entirely in the border colour (rows above/below the image).
#define BORDER_LINE_COLOUR_WORD 9
static uint32_t border_line[] = {
    HBLANK_CMDS(1),
    HSTX_CMD_TMDS_REPEAT | DVI_ACTIVE_WIDTH, 0,
    HSTX_CMD_NOP,
};

// Image row: blanking, left border, 640 RGB888 pixels, right border. Each
// row is expanded once and sent on both of its lines, from buffer
// (row & 1): the other buffer's row is still being sent.
#define IMAGE_PIXEL_WORDS AMIGA_SOURCE_WIDTH
enum {
    IMAGE_LINE_HEADER = 8,
    IMAGE_LINE_LEFT = IMAGE_LINE_HEADER,          // TMDS_REPEAT, colour
    IMAGE_LINE_PIXELS_CMD = IMAGE_LINE_LEFT + 2,  // TMDS | 640
    IMAGE_LINE_PIXELS = IMAGE_LINE_PIXELS_CMD + 1,
    IMAGE_LINE_RIGHT = IMAGE_LINE_PIXELS + IMAGE_PIXEL_WORDS,
    IMAGE_LINE_WORDS = IMAGE_LINE_RIGHT + 2,
};
static uint32_t image_lines[2][IMAGE_LINE_WORDS] __attribute__((aligned(4)));

// Scanout state of the displayed indexed frame: the palette after
// scan_applied log entries, as RGB888 (32..63 extra half-brite).
static uint32_t scan_palette[64];
static uint32_t scan_applied;
// Branchless HAM:
//   next = (previous & scan_ham_keep[code >> 4]) | scan_ham_set[code].
// Codes 0x00..0x0f load a colour register (keep nothing), 0x10/0x20/0x30
// replace blue/red/green.
static uint32_t scan_ham_keep[4] = { 0u, 0xffff00u, 0x00ffffu, 0xff00ffu };
static uint32_t scan_ham_set[64];

static void dvi_init_ham_tables(void) {
    static const uint8_t shift[4] = { 0, 0, 16, 8 };
    for (uint code = 0; code < 64u; ++code) {
        if (code >= 16u)
            scan_ham_set[code] = (code & 0xfu) * 0x11u << shift[code >> 4];
    }
}

// Loops here must not become libc calls (flash code) inside the interrupt.
#define SCAN_FUNC(name) \
    __attribute__((optimize("no-tree-loop-distribute-patterns"))) \
    __not_in_flash_func(name)

static inline void scan_set_register(uint32_t reg, uint32_t colour) {
    const uint32_t rgb = ocs_rgb888(colour);
    scan_palette[reg] = rgb;
    scan_palette[reg + 32u] = ocs_rgb888((colour >> 1) & 0x777u);
    if (reg < 16u)
        scan_ham_set[reg] = rgb;
}

static void SCAN_FUNC(scan_begin_frame)(int frame) {
    if (!frame_indexed[frame])
        return;
    const dvi_indexed_frame_t *rec = &frame_records[frame];
    for (uint32_t i = 0; i < 32u; ++i)
        scan_set_register(i, rec->initial_palette[i]);
    scan_applied = 0;
}

static inline void scan_apply_log(const dvi_indexed_frame_t *rec,
                                  uint32_t pos) {
    while (scan_applied < pos) {
        const uint32_t entry = rec->palette_log[scan_applied++];
        scan_set_register(entry >> 12, entry & 0xfffu);
    }
}

static inline void scan_fill(uint32_t *out, uint32_t x0, uint32_t x1,
                             uint32_t colour) {
    for (uint32_t x = x0; x < x1; ++x)
        out[x] = colour;
}

static void SCAN_FUNC(scan_indexed)(uint32_t *out, const uint8_t *row,
                                    uint32_t x0, uint32_t x1) {
    const uint32_t *palette = scan_palette;
    uint32_t x = x0;
    for (; x < x1 && (x & 3u); ++x)
        out[x] = palette[row[x] & 63u];
    // Four pixels per word load.
    for (; x + 4u <= x1; x += 4u) {
        const uint32_t four = *(const uint32_t *)&row[x];
        out[x] = palette[four & 63u];
        out[x + 1u] = palette[(four >> 8) & 63u];
        out[x + 2u] = palette[(four >> 16) & 63u];
        out[x + 3u] = palette[(four >> 24) & 63u];
    }
    for (; x < x1; ++x)
        out[x] = palette[row[x] & 63u];
}

// HAM is LORES only, so every code covers an aligned pair of columns;
// decode each pair once. Odd bounds fall back to single pixels. A sprite
// pixel (0x40 | register) shows that colour register and leaves the held
// colour alone, as on real hardware.
static inline uint32_t scan_ham_pixel(uint32_t code, uint32_t *hold) {
    if (code & 0x40u)
        return scan_palette[code & 0x1fu];
    code &= 63u;
    *hold = (*hold & scan_ham_keep[code >> 4]) | scan_ham_set[code];
    return *hold;
}

static uint32_t SCAN_FUNC(scan_ham)(uint32_t *out, const uint8_t *row,
                                    uint32_t x0, uint32_t x1, uint32_t hold) {
    if ((x0 | x1) & 1u) {
        for (uint32_t x = x0; x < x1; ++x)
            out[x] = scan_ham_pixel(row[x], &hold);
        return hold;
    }
    for (uint32_t x = x0; x < x1; x += 2u) {
        const uint32_t pixel = scan_ham_pixel(row[x], &hold);
        out[x] = pixel;
        out[x + 1u] = pixel;
    }
    return hold;
}

// Expands image row y of `frame` into out[0..640); returns the row's
// border colour.
static uint32_t SCAN_FUNC(scan_expand_row)(int frame, uint y, uint32_t *out) {
    const uint8_t *row = dvi_image_row(source_frames[frame], y);
    if (!frame_indexed[frame]) {
        for (uint x = 0; x < AMIGA_SOURCE_WIDTH; ++x)
            out[x] = rgb332_rgb888[row[x]];
        return frame_border[frame];
    }
    const dvi_indexed_frame_t *rec = &frame_records[frame];
    const uint32_t first = rec->row_segment[y];
    const uint32_t last = rec->row_segment[y + 1u];
    if (first == last) {
        if (rec->segment_overflow && first == rec->segments_used)
            scan_indexed(out, row, 0, AMIGA_SOURCE_WIDTH);
        else
            scan_fill(out, 0, AMIGA_SOURCE_WIDTH, scan_palette[0]);
        return scan_palette[0];
    }
    // Columns outside the drawn runs show COLOR00 as the row began.
    scan_apply_log(rec, DVI_SEGMENT_POS(rec->segment[first]));
    const uint32_t border = scan_palette[0];
    uint32_t min = AMIGA_SOURCE_WIDTH, max = 0;
    for (uint32_t i = first; i < last; ++i) {
        const uint32_t seg = rec->segment[i];
        if (DVI_SEGMENT_X0(seg) < min) min = DVI_SEGMENT_X0(seg);
        if (DVI_SEGMENT_X1(seg) > max) max = DVI_SEGMENT_X1(seg);
    }
    scan_fill(out, 0, min, border);
    scan_fill(out, max, AMIGA_SOURCE_WIDTH, border);
    // Runs in drawing order, so the palette log only moves forward; HAM
    // holds its colour across runs, starting from COLOR00.
    uint32_t hold = border;
    for (uint32_t i = first; i < last; ++i) {
        const uint32_t seg = rec->segment[i];
        scan_apply_log(rec, DVI_SEGMENT_POS(seg));
        if (DVI_SEGMENT_HAM(seg))
            hold = scan_ham(out, row, DVI_SEGMENT_X0(seg),
                            DVI_SEGMENT_X1(seg), hold);
        else
            scan_indexed(out, row, DVI_SEGMENT_X0(seg), DVI_SEGMENT_X1(seg));
    }
    return border;
}

static uint hstx_dma[2];
static uint hstx_next_line;
static int hstx_active_frame;

static void hstx_init_line_buffers(void) {
    static const uint32_t header[IMAGE_LINE_HEADER] = { HBLANK_CMDS(1) };
    for (uint i = 0; i < 2; ++i) {
        uint32_t *line = image_lines[i];
        memcpy(line, header, sizeof(header));
        // 640-wide modes have no side border: NOPs instead.
        const uint32_t border_cmd = DVI_IMAGE_X0
            ? HSTX_CMD_TMDS_REPEAT | DVI_IMAGE_X0 : HSTX_CMD_NOP;
        line[IMAGE_LINE_LEFT] = border_cmd;
        line[IMAGE_LINE_LEFT + 1] = HSTX_CMD_NOP;
        line[IMAGE_LINE_PIXELS_CMD] = HSTX_CMD_TMDS | AMIGA_SOURCE_WIDTH;
        line[IMAGE_LINE_RIGHT] = border_cmd;
        line[IMAGE_LINE_RIGHT + 1] = HSTX_CMD_NOP;
    }
}

// Points DMA channel `index` at the next line; called for the channel that
// just finished, while the other channel is still sending its line.
static void __not_in_flash_func(hstx_program_next)(uint index) {
    const uint line = hstx_next_line;
    hstx_next_line = line + 1u == MODE_V_TOTAL_LINES ? 0u : line + 1u;

    if (line == 0u) {
        // Switch to the pending frame unless core 0 just took it back.
        uint32_t state = __atomic_load_n(&frame_state, __ATOMIC_ACQUIRE);
        if ((state & FRAME_PENDING) &&
            __atomic_compare_exchange_n(&frame_state, &state,
                                        (state & 1u) ^ 1u, false,
                                        __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE)) {
            hstx_active_frame = (int)((state & 1u) ^ 1u);
            dvi_frames_shown++;
        }
        border_line[BORDER_LINE_COLOUR_WORD] = frame_border[hstx_active_frame];
        scan_begin_frame(hstx_active_frame);
    }

    const uint32_t *list;
    uint count;
    int expand_y = -1;
    if (line < MODE_V_ACTIVE_LINES) {
        const uint image_y = line / 2u - DVI_IMAGE_Y0;
        if (image_y < AMIGA_SOURCE_HEIGHT) {
            uint32_t *out = image_lines[image_y & 1u];
            // The first line of each row expands it; the second resends it.
            if (!(line & 1u))
                expand_y = (int)image_y;
            list = out;
            count = IMAGE_LINE_WORDS;
        } else {
            list = border_line;
            count = count_of(border_line);
        }
    } else if (line >= MODE_V_ACTIVE_LINES + MODE_V_FRONT_PORCH &&
               line < MODE_V_ACTIVE_LINES + MODE_V_FRONT_PORCH +
                      MODE_V_SYNC_WIDTH) {
        list = vsync_line;
        count = count_of(vsync_line);
    } else {
        list = vblank_line;
        count = count_of(vblank_line);
    }
    dma_channel_hw_t *ch = &dma_hw->ch[hstx_dma[index]];
    ch->read_addr = (uintptr_t)list;
    ch->transfer_count = count;

    // Expand after reprogramming: this channel starts only when the other
    // finishes its line, and the line's commands never change, so a late
    // expansion can at worst tear a row, never lose sync.
    if (expand_y >= 0) {
        uint32_t *out = image_lines[expand_y & 1];
        const uint32_t border = scan_expand_row(
            hstx_active_frame, (uint)expand_y, out + IMAGE_LINE_PIXELS);
        if (DVI_IMAGE_X0) {
            out[IMAGE_LINE_LEFT + 1] = border;
            out[IMAGE_LINE_RIGHT + 1] = border;
        }
    }
}

static void __not_in_flash_func(hstx_dma_irq)(void) {
    for (uint index = 0; index < 2u; ++index) {
        const uint32_t mask = 1u << hstx_dma[index];
        if (dma_hw->ints1 & mask) {
            dma_hw->ints1 = mask;
            hstx_program_next(index);
        }
    }
}

static void hstx_configure(void) {
    // Output two bits per clk_hstx cycle: a 10-bit TMDS symbol every five
    // cycles, so clk_hstx is half the TMDS bit rate.
    hstx_ctrl_hw->csr = 0;
    hstx_ctrl_hw->csr =
        HSTX_CTRL_CSR_EXPAND_EN_BITS |
        5u << HSTX_CTRL_CSR_CLKDIV_LSB |
        5u << HSTX_CTRL_CSR_N_SHIFTS_LSB |
        2u << HSTX_CTRL_CSR_SHIFT_LSB |
        HSTX_CTRL_CSR_EN_BITS;
    // RGB888: red bits 23:16 (lane 2), green 15:8 (lane 1), blue 7:0
    // (lane 0); each lane encodes bits 7:0 of the word rotated right.
    hstx_ctrl_hw->expand_tmds =
        7u << HSTX_CTRL_EXPAND_TMDS_L2_NBITS_LSB |
        16u << HSTX_CTRL_EXPAND_TMDS_L2_ROT_LSB |
        7u << HSTX_CTRL_EXPAND_TMDS_L1_NBITS_LSB |
        8u << HSTX_CTRL_EXPAND_TMDS_L1_ROT_LSB |
        7u << HSTX_CTRL_EXPAND_TMDS_L0_NBITS_LSB |
        0u << HSTX_CTRL_EXPAND_TMDS_L0_ROT_LSB;
    // One pixel per data word; control words are raw 30-bit symbols.
    hstx_ctrl_hw->expand_shift =
        1u << HSTX_CTRL_EXPAND_SHIFT_ENC_N_SHIFTS_LSB |
        0u << HSTX_CTRL_EXPAND_SHIFT_ENC_SHIFT_LSB |
        1u << HSTX_CTRL_EXPAND_SHIFT_RAW_N_SHIFTS_LSB |
        0u << HSTX_CTRL_EXPAND_SHIFT_RAW_SHIFT_LSB;

    // HSTX output bits 0..7 are GPIO12..19. Place each differential pair at
    // the board's pin (P = pin, N = pin + 1, N inverted).
    const uint clk_bit = BOARD_DVI_TMDS_CLK_PIN - 12u;
    hstx_ctrl_hw->bit[clk_bit] = HSTX_CTRL_BIT0_CLK_BITS;
    hstx_ctrl_hw->bit[clk_bit + 1u] =
        HSTX_CTRL_BIT0_CLK_BITS | HSTX_CTRL_BIT0_INV_BITS;
    const uint lane_pins[3] = {
        BOARD_DVI_TMDS_D0_PIN, BOARD_DVI_TMDS_D1_PIN, BOARD_DVI_TMDS_D2_PIN,
    };
    for (uint lane = 0; lane < 3u; ++lane) {
        const uint bit = lane_pins[lane] - 12u;
        // Even symbol bits in the first half of each clk_hstx cycle, odd
        // bits in the second half.
        const uint32_t sel =
            (lane * 10u) << HSTX_CTRL_BIT0_SEL_P_LSB |
            (lane * 10u + 1u) << HSTX_CTRL_BIT0_SEL_N_LSB;
        hstx_ctrl_hw->bit[bit] = sel;
        hstx_ctrl_hw->bit[bit + 1u] = sel | HSTX_CTRL_BIT0_INV_BITS;
    }
    for (uint pin = 12u; pin <= 19u; ++pin)
        gpio_set_function(pin, GPIO_FUNC_HSTX);
}

static void hstx_start(void) {
    hstx_init_line_buffers();
    hstx_active_frame = (int)(frame_state & 1u);
    hstx_next_line = 0;
    for (uint index = 0; index < 2u; ++index) {
        dma_channel_config c = dma_channel_get_default_config(hstx_dma[index]);
        channel_config_set_chain_to(&c, hstx_dma[index ^ 1u]);
        channel_config_set_dreq(&c, DREQ_HSTX);
        dma_channel_configure(hstx_dma[index], &c, &hstx_fifo_hw->fifo,
                              vblank_line, count_of(vblank_line), false);
        hstx_program_next(index); // lines 0 and 1
    }
    // The interrupt runs on this core (core 1); core 0 never sees it.
    dma_hw->ints1 = (1u << hstx_dma[0]) | (1u << hstx_dma[1]);
    dma_hw->inte1 = (1u << hstx_dma[0]) | (1u << hstx_dma[1]);
    irq_set_exclusive_handler(DMA_IRQ_1, hstx_dma_irq);
    irq_set_enabled(DMA_IRQ_1, true);
    hstx_configure();
    dma_channel_start(hstx_dma[0]);
}

static void dvi_core1(void) {
    // Notify core 0 that runtime_run_per_core_initializers() has completed.
    multicore_fifo_push_blocking(0u);
    // Wait until core 0 has filled the frames with the boot pattern.
    multicore_fifo_pop_blocking();
    hstx_start();
    multicore_fifo_push_blocking(0u);
    // Between line interrupts, convert the emulator's bitplane blocks into
    // the scanout frame (src/Host.c).
    hostCore1Loop();
}

void dvi_display_init(void) {
    source_frames[0] = sram_frames[0];
    source_frames[1] = sram_frames[1];
    source_frame_has_emulator[0] = false;
    source_frame_has_emulator[1] = false;
    frame_indexed[0] = frame_indexed[1] = false;
    frame_state = 0;
    dvi_init_rgb332_table();
    dvi_init_ham_tables();

    // main.c runs PLL_USB at the TMDS bit rate. Two bits leave per clk_hstx
    // cycle, so clk_hstx = PLL_USB / 2 (126 MHz NTSC, 135 MHz PAL), and
    // clk_sys stays free for the emulator.
    const uint32_t bit_hz = MODE_BIT_CLK_KHZ * 1000u;
    const uint32_t pll_usb_khz =
        frequency_count_khz(CLOCKS_FC0_SRC_VALUE_PLL_USB_CLKSRC_PRIMARY);
    if (pll_usb_khz + 1000u < MODE_BIT_CLK_KHZ ||
        pll_usb_khz > MODE_BIT_CLK_KHZ + 1000u ||
        !clock_configure(clk_hstx, 0,
                         CLOCKS_CLK_HSTX_CTRL_AUXSRC_VALUE_CLKSRC_PLL_USB,
                         bit_hz, bit_hz / 2u))
        panic("HSTX clock does not match the DVI mode");
    // The SDK's runtime init leaves HSTX in reset; release it once its
    // clock runs, before core 1 configures it.
    reset_unreset_block_num_wait_blocking(RESET_HSTX);
    hstx_dma[0] = (uint)dma_claim_unused_channel(true);
    hstx_dma[1] = (uint)dma_claim_unused_channel(true);
    multicore_launch_core1(dvi_core1);
}

static void dvi_fill_boot_pattern(uint8_t *frame) {
    static const uint8_t bars[8] = {
        0xe0, // red
        0xfc, // yellow
        0x1c, // green
        0x1f, // cyan
        0x03, // blue
        0xe3, // magenta
        0xff, // white
        0x00, // black
    };

    for (uint y = 0; y < DVI_FRAME_H; ++y) {
        for (uint x = 0; x < DVI_FRAME_W; ++x) {
            uint8_t pixel = bars[(x * count_of(bars)) / DVI_FRAME_W];
            // White frame makes cropping and vertical stability obvious.
            if (x < 4u || x >= DVI_FRAME_W - 4u ||
                y < 4u || y >= DVI_FRAME_H - 4u)
                pixel = 0xffu;
            frame[y * DVI_FRAME_W + x] = pixel;
        }
    }
}

void dvi_display_start(void) {
    dvi_fill_boot_pattern(source_frames[0]);
    dvi_fill_boot_pattern(source_frames[1]);
    boot_pattern_until_us = time_us_64() + 1500000u;
    boot_pattern_until_lo = (uint32_t)boot_pattern_until_us;
    boot_pattern_armed = true;

    // Frame presentation performs large PSRAM writes on core 0. Give scanout
    // and its DMA channels priority so those writes cannot starve it.
    hw_set_bits(&busctrl_hw->priority,
                BUSCTRL_BUS_PRIORITY_PROC1_BITS |
                BUSCTRL_BUS_PRIORITY_DMA_R_BITS |
                BUSCTRL_BUS_PRIORITY_DMA_W_BITS);
    hw_clear_bits(&busctrl_hw->priority, BUSCTRL_BUS_PRIORITY_PROC0_BITS);
    while (!busctrl_hw->priority_ack)
        tight_loop_contents();

    multicore_fifo_push_blocking(0u);
    multicore_fifo_pop_blocking();
    printf("DVI: HSTX %s emulator scanout on %s\n",
           DVI_MODE_NAME, BOARD_DVI_PIN_RANGE);
}
