// DVI/HDMI scanout through the RP2350 HSTX peripheral (WeAct GPIO12..19).
//
// HSTX TMDS-encodes RGB332 pixels in hardware. Two ping-pong DMA channels
// feed it one scanline at a time; core 1 only services one DMA interrupt per
// line. Core 0 fills double-buffered RGB332 frames in SRAM, and core 1
// changes buffers only at a DVI frame boundary.

#include "dvi_display.h"
#include "board_config.h"
#include "Host.h"
#include "../omega/VideoStandard.h"

#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/resets.h"
#include "hardware/structs/busctrl.h"
#include "hardware/structs/hstx_ctrl.h"
#include "hardware/structs/hstx_fifo.h"
#include "hardware/sync.h"
#include "pico/multicore.h"
#include "pico/stdlib.h"

#include <stdio.h>
#include <string.h>

#if OMEGA_VIDEO_STANDARD == OMEGA_VIDEO_PAL
// CEA 720x576p50: 27 MHz pixel clock, 864x625 total pixels.
#define MODE_H_FRONT_PORCH 12u
#define MODE_H_SYNC_WIDTH  64u
#define MODE_H_BACK_PORCH  68u
#define MODE_V_FRONT_PORCH 5u
#define MODE_V_SYNC_WIDTH  5u
#define MODE_V_BACK_PORCH  39u
#define MODE_BIT_CLK_KHZ   270000u
#define DVI_ACTIVE_WIDTH   720u
#define DVI_MODE_NAME      "720x576p50"
#define SOURCE_HEIGHT      288u
// PAL screens such as Workbench use 256 lines; showing only 200 cut off the
// lower edge of windows.
#define AMIGA_SOURCE_HEIGHT 256u
#else
// NTSC builds run clk_sys at 252 MHz, which is exactly VGA 640x480p60
// (25.2 MHz pixels, 252 Mbit/s). A 720x480p60 mode would need 270 MHz; at
// 252 MHz it was a non-standard ~55.9 Hz mode that capture devices locked onto
// unreliably. 640 active pixels also match the Amiga image without borders.
#define MODE_H_FRONT_PORCH 16u
#define MODE_H_SYNC_WIDTH  96u
#define MODE_H_BACK_PORCH  48u
#define MODE_V_FRONT_PORCH 10u
#define MODE_V_SYNC_WIDTH  2u
#define MODE_V_BACK_PORCH  33u
#define MODE_BIT_CLK_KHZ   252000u
#define DVI_ACTIVE_WIDTH   640u
#define DVI_MODE_NAME      "640x480p60"
#define SOURCE_HEIGHT      240u
// Use every row of the 480-line mode: overscan screens (e.g. xsysinfo) run
// to the end of the NTSC frame, beyond 200 lines.
#define AMIGA_SOURCE_HEIGHT 240u
#endif
// Each stored row is sent on two consecutive lines.
#define MODE_V_ACTIVE_LINES (SOURCE_HEIGHT * 2u)

#define AMIGA_SOURCE_WIDTH 640u
#define DVI_IMAGE_X0 ((DVI_ACTIVE_WIDTH - AMIGA_SOURCE_WIDTH) / 2u)
#define DVI_IMAGE_Y0 ((SOURCE_HEIGHT - AMIGA_SOURCE_HEIGHT) / 2u)

// The image frames live in SRAM: the emulator saturates the shared QMI bus,
// and PSRAM line fetches used to miss the scanline deadline. Only the
// 640-wide image is stored; the borders are generated by HSTX commands.
#define DVI_FRAME_W AMIGA_SOURCE_WIDTH
#define DVI_FRAME_H AMIGA_SOURCE_HEIGHT
#define DVI_FRAME_BYTES (DVI_FRAME_W * DVI_FRAME_H)
static uint8_t sram_frames[2][DVI_FRAME_BYTES] __attribute__((aligned(4)));

static uint8_t *source_frames[2];
static bool source_frame_has_emulator[2];
static volatile int displayed_frame;
static volatile int pending_frame;
static uint64_t boot_pattern_until_us;
// Border colour (COLOR00) of each frame. Like a real Amiga, the areas around
// the image show the border colour rather than black.
static uint8_t frame_border[2];

// Returns the first pixel of image row y (0..AMIGA_SOURCE_HEIGHT-1).
static inline uint8_t *dvi_image_row(uint8_t *frame, uint y) {
    return frame + y * DVI_FRAME_W;
}

static bool dvi_begin_submit(int *target_out, uint8_t **dst_out) {
    // Keep the diagnostic pattern visible long enough to distinguish DVI
    // bring-up from emulator video on a monitor or capture device.
    if (time_us_64() < boot_pattern_until_us)
        return false;

    if (__atomic_load_n(&pending_frame, __ATOMIC_ACQUIRE) >= 0)
        return false;

    int target = __atomic_load_n(&displayed_frame, __ATOMIC_ACQUIRE) ^ 1;
    uint8_t *dst = source_frames[target];
    if (!source_frame_has_emulator[target]) {
        memset(dst, 0, DVI_FRAME_BYTES);
        source_frame_has_emulator[target] = true;
    }
    *target_out = target;
    *dst_out = dst;
    return true;
}

static void dvi_publish_frame(int target) {
    __atomic_store_n(&pending_frame, target, __ATOMIC_RELEASE);
}

static int direct_target = -1;

int dvi_display_direct_height(void) {
    return AMIGA_SOURCE_HEIGHT;
}

uint8_t *dvi_display_direct_acquire(void) {
    if (time_us_64() < boot_pattern_until_us)
        return NULL;
    // Core 1 takes a queued frame at its next frame boundary, so this waits
    // at most one DVI frame. The other buffer is then free until published.
    while (__atomic_load_n(&pending_frame, __ATOMIC_ACQUIRE) >= 0)
        tight_loop_contents();
    direct_target = __atomic_load_n(&displayed_frame, __ATOMIC_ACQUIRE) ^ 1;
    source_frame_has_emulator[direct_target] = true;
    return source_frames[direct_target];
}

void dvi_display_direct_publish(uint32_t border) {
    if (direct_target < 0)
        return;
    frame_border[direct_target] = dvi_rgb332(border);
    dvi_publish_frame(direct_target);
    direct_target = -1;
}

bool dvi_display_submit_frame(const uint32_t *argb_frame) {
    // Never overwrite a buffer that is displayed or already queued. With two
    // buffers, dropping a late producer frame is safer than tearing scanout.
    int target;
    uint8_t *dst;
    if (!dvi_begin_submit(&target, &dst))
        return false;

    // The presented frame's corner always holds the border colour.
    const uint8_t border_pixel = dvi_rgb332(argb_frame[0]);
    frame_border[target] = border_pixel;
    for (uint y = 0; y < AMIGA_SOURCE_HEIGHT; ++y) {
        uint8_t *dst_row = dvi_image_row(dst, y);
        // The presented framebuffer holds SCREEN_H / 2 logical rows.
        if (y >= SCREEN_H / 2u) {
            memset(dst_row, border_pixel, AMIGA_SOURCE_WIDTH);
            continue;
        }
        const uint32_t *src_row = argb_frame + (y * 2u) * SCREEN_W;
        for (uint x = 0; x < AMIGA_SOURCE_WIDTH; ++x)
            dst_row[x] = dvi_rgb332(src_row[x]);
    }

    dvi_publish_frame(target);
    return true;
}

bool dvi_display_submit_raster(const uint32_t *argb_raster,
                               const int16_t *row_min,
                               const int16_t *row_max,
                               uint32_t border,
                               int source_step,
                               int y_offset,
                               int row_rotation) {
    int target;
    uint8_t *dst;
    if (!dvi_begin_submit(&target, &dst))
        return false;

    const uint8_t border_pixel = dvi_rgb332(border);
    frame_border[target] = border_pixel;
    const int first_source_y = y_offset / 2;
    const int source_rows = HOST_RASTER_H / source_step;

    for (int y = 0; y < AMIGA_SOURCE_HEIGHT; ++y) {
        uint8_t *dst_row = dvi_image_row(dst, (uint)y);
        int source_y = y - first_source_y;
        if (source_y < 0 || source_y >= source_rows) {
            memset(dst_row, border_pixel, AMIGA_SOURCE_WIDTH);
            continue;
        }

        const int raster_row = source_y * source_step;
        const int written_min = row_min[raster_row];
        const unsigned written_width =
            (unsigned)(row_max[raster_row] - written_min);
        if (row_max[raster_row] <= written_min) {
            memset(dst_row, border_pixel, AMIGA_SOURCE_WIDTH);
            continue;
        }
        const uint32_t *src_row = argb_raster + raster_row * SCREEN_W;
        for (int x = 0; x < AMIGA_SOURCE_WIDTH; ++x) {
            int source_x = x + row_rotation;
            if (source_x >= SCREEN_W)
                source_x -= SCREEN_W;
            // Pixels outside this frame's written range are stale; the
            // raster is no longer cleared between frames.
            dst_row[x] = (unsigned)(source_x - written_min) < written_width
                       ? dvi_rgb332(src_row[source_x])
                       : border_pixel;
        }
    }

    dvi_publish_frame(target);
    return true;
}

// ── HSTX scanout ──────────────────────────────────────────────────────────
// TMDS control symbols; lane 0 carries HSYNC (C0) and VSYNC (C1). Both
// supported modes use negative sync polarity, so the idle level is 1.
#define TMDS_CTRL_00 0x354u
#define TMDS_CTRL_01 0x0abu
#define TMDS_CTRL_10 0x154u
#define TMDS_CTRL_11 0x2abu
#define SYNC_V0_H0 (TMDS_CTRL_00 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))
#define SYNC_V0_H1 (TMDS_CTRL_01 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))
#define SYNC_V1_H0 (TMDS_CTRL_10 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))
#define SYNC_V1_H1 (TMDS_CTRL_11 | (TMDS_CTRL_00 << 10) | (TMDS_CTRL_00 << 20))

#define HSTX_CMD_RAW_REPEAT  (0x1u << 12)
#define HSTX_CMD_TMDS        (0x2u << 12)
#define HSTX_CMD_TMDS_REPEAT (0x3u << 12)
#define HSTX_CMD_NOP         (0xfu << 12)

// Lines are ordered active first, then the vertical blanking interval.
#define MODE_V_TOTAL_LINES (MODE_V_ACTIVE_LINES + MODE_V_FRONT_PORCH + \
                            MODE_V_SYNC_WIDTH + MODE_V_BACK_PORCH)

#define HBLANK_CMDS(vsync)                                      \
    HSTX_CMD_RAW_REPEAT | MODE_H_FRONT_PORCH, SYNC_V##vsync##_H1, \
    HSTX_CMD_NOP,                                               \
    HSTX_CMD_RAW_REPEAT | MODE_H_SYNC_WIDTH, SYNC_V##vsync##_H0,  \
    HSTX_CMD_NOP,                                               \
    HSTX_CMD_RAW_REPEAT | MODE_H_BACK_PORCH, SYNC_V##vsync##_H1

static uint32_t vblank_line[] = {
    HBLANK_CMDS(1),
    HSTX_CMD_RAW_REPEAT | DVI_ACTIVE_WIDTH, SYNC_V1_H1,
    HSTX_CMD_NOP,
};
static uint32_t vsync_line[] = {
    HBLANK_CMDS(0),
    HSTX_CMD_RAW_REPEAT | DVI_ACTIVE_WIDTH, SYNC_V0_H1,
    HSTX_CMD_NOP,
};
// Active line entirely in the border colour (rows above/below the image).
#define BORDER_LINE_COLOUR_WORD 9
static uint32_t border_line[] = {
    HBLANK_CMDS(1),
    HSTX_CMD_TMDS_REPEAT | DVI_ACTIVE_WIDTH, 0,
    HSTX_CMD_NOP,
};

// Image line: blanking, left border, 640 pixels, right border. Each DMA
// channel owns one, refilled from the SRAM frame while the other is sent.
#define IMAGE_PIXEL_WORDS (AMIGA_SOURCE_WIDTH / 4u)
enum {
    IMAGE_LINE_HEADER = 8,
    IMAGE_LINE_LEFT = IMAGE_LINE_HEADER,          // TMDS_REPEAT, colour
    IMAGE_LINE_PIXELS_CMD = IMAGE_LINE_LEFT + 2,  // TMDS | 640
    IMAGE_LINE_PIXELS = IMAGE_LINE_PIXELS_CMD + 1,
    IMAGE_LINE_RIGHT = IMAGE_LINE_PIXELS + IMAGE_PIXEL_WORDS,
    IMAGE_LINE_WORDS = IMAGE_LINE_RIGHT + 2,
};
static uint32_t image_lines[2][IMAGE_LINE_WORDS] __attribute__((aligned(4)));

static uint hstx_dma[2];
static uint hstx_next_line;
static int hstx_active_frame;
static uint32_t hstx_border_word;

static void hstx_init_line_buffers(void) {
    static const uint32_t header[IMAGE_LINE_HEADER] = { HBLANK_CMDS(1) };
    for (uint i = 0; i < 2; ++i) {
        uint32_t *line = image_lines[i];
        memcpy(line, header, sizeof(header));
        // 640-wide modes have no side border: NOPs instead.
        const uint32_t border_cmd = DVI_IMAGE_X0
            ? HSTX_CMD_TMDS_REPEAT | DVI_IMAGE_X0 : HSTX_CMD_NOP;
        line[IMAGE_LINE_LEFT] = border_cmd;
        line[IMAGE_LINE_LEFT + 1] = HSTX_CMD_NOP;
        line[IMAGE_LINE_PIXELS_CMD] = HSTX_CMD_TMDS | AMIGA_SOURCE_WIDTH;
        line[IMAGE_LINE_RIGHT] = border_cmd;
        line[IMAGE_LINE_RIGHT + 1] = HSTX_CMD_NOP;
    }
}

// Points DMA channel `index` at the next line; called for the channel that
// just finished, while the other channel is still sending its line.
static void __not_in_flash_func(hstx_program_next)(uint index) {
    const uint line = hstx_next_line;
    hstx_next_line = line + 1u == MODE_V_TOTAL_LINES ? 0u : line + 1u;

    if (line == 0u) {
        int next = __atomic_load_n(&pending_frame, __ATOMIC_ACQUIRE);
        if (next >= 0) {
            hstx_active_frame = next;
            // Publish the new consumer before freeing the old buffer.
            __atomic_store_n(&displayed_frame, next, __ATOMIC_RELEASE);
            __atomic_store_n(&pending_frame, -1, __ATOMIC_RELEASE);
        }
        hstx_border_word = frame_border[hstx_active_frame] * 0x01010101u;
        border_line[BORDER_LINE_COLOUR_WORD] = hstx_border_word;
    }

    const uint32_t *list;
    uint count;
    if (line < MODE_V_ACTIVE_LINES) {
        const uint image_y = line / 2u - DVI_IMAGE_Y0;
        if (image_y < AMIGA_SOURCE_HEIGHT) {
            uint32_t *out = image_lines[index];
            const uint32_t *row = (const uint32_t *)dvi_image_row(
                source_frames[hstx_active_frame], image_y);
            for (uint i = 0; i < IMAGE_PIXEL_WORDS; ++i)
                out[IMAGE_LINE_PIXELS + i] = row[i];
            if (DVI_IMAGE_X0) {
                out[IMAGE_LINE_LEFT + 1] = hstx_border_word;
                out[IMAGE_LINE_RIGHT + 1] = hstx_border_word;
            }
            list = out;
            count = IMAGE_LINE_WORDS;
        } else {
            list = border_line;
            count = count_of(border_line);
        }
    } else if (line >= MODE_V_ACTIVE_LINES + MODE_V_FRONT_PORCH &&
               line < MODE_V_ACTIVE_LINES + MODE_V_FRONT_PORCH +
                      MODE_V_SYNC_WIDTH) {
        list = vsync_line;
        count = count_of(vsync_line);
    } else {
        list = vblank_line;
        count = count_of(vblank_line);
    }
    dma_channel_hw_t *ch = &dma_hw->ch[hstx_dma[index]];
    ch->read_addr = (uintptr_t)list;
    ch->transfer_count = count;
}

static void __not_in_flash_func(hstx_dma_irq)(void) {
    for (uint index = 0; index < 2u; ++index) {
        const uint32_t mask = 1u << hstx_dma[index];
        if (dma_hw->ints1 & mask) {
            dma_hw->ints1 = mask;
            hstx_program_next(index);
        }
    }
}

static void hstx_configure(void) {
    // Output two bits per clk_hstx cycle: a 10-bit TMDS symbol every five
    // cycles, so clk_hstx is half the TMDS bit rate.
    hstx_ctrl_hw->csr = 0;
    hstx_ctrl_hw->csr =
        HSTX_CTRL_CSR_EXPAND_EN_BITS |
        5u << HSTX_CTRL_CSR_CLKDIV_LSB |
        5u << HSTX_CTRL_CSR_N_SHIFTS_LSB |
        2u << HSTX_CTRL_CSR_SHIFT_LSB |
        HSTX_CTRL_CSR_EN_BITS;
    // RGB332: red bits 7:5 (lane 2), green 4:2 (lane 1), blue 1:0 (lane 0).
    hstx_ctrl_hw->expand_tmds =
        2u << HSTX_CTRL_EXPAND_TMDS_L2_NBITS_LSB |
        0u << HSTX_CTRL_EXPAND_TMDS_L2_ROT_LSB |
        2u << HSTX_CTRL_EXPAND_TMDS_L1_NBITS_LSB |
        29u << HSTX_CTRL_EXPAND_TMDS_L1_ROT_LSB |
        1u << HSTX_CTRL_EXPAND_TMDS_L0_NBITS_LSB |
        26u << HSTX_CTRL_EXPAND_TMDS_L0_ROT_LSB;
    // Four 8-bit pixels per data word; control words are raw 30-bit symbols.
    hstx_ctrl_hw->expand_shift =
        4u << HSTX_CTRL_EXPAND_SHIFT_ENC_N_SHIFTS_LSB |
        8u << HSTX_CTRL_EXPAND_SHIFT_ENC_SHIFT_LSB |
        1u << HSTX_CTRL_EXPAND_SHIFT_RAW_N_SHIFTS_LSB |
        0u << HSTX_CTRL_EXPAND_SHIFT_RAW_SHIFT_LSB;

    // HSTX output bits 0..7 are GPIO12..19. Place each differential pair at
    // the board's pin (P = pin, N = pin + 1, N inverted).
    const uint clk_bit = BOARD_DVI_TMDS_CLK_PIN - 12u;
    hstx_ctrl_hw->bit[clk_bit] = HSTX_CTRL_BIT0_CLK_BITS;
    hstx_ctrl_hw->bit[clk_bit + 1u] =
        HSTX_CTRL_BIT0_CLK_BITS | HSTX_CTRL_BIT0_INV_BITS;
    const uint lane_pins[3] = {
        BOARD_DVI_TMDS_D0_PIN, BOARD_DVI_TMDS_D1_PIN, BOARD_DVI_TMDS_D2_PIN,
    };
    for (uint lane = 0; lane < 3u; ++lane) {
        const uint bit = lane_pins[lane] - 12u;
        // Even symbol bits in the first half of each clk_hstx cycle, odd
        // bits in the second half.
        const uint32_t sel =
            (lane * 10u) << HSTX_CTRL_BIT0_SEL_P_LSB |
            (lane * 10u + 1u) << HSTX_CTRL_BIT0_SEL_N_LSB;
        hstx_ctrl_hw->bit[bit] = sel;
        hstx_ctrl_hw->bit[bit + 1u] = sel | HSTX_CTRL_BIT0_INV_BITS;
    }
    for (uint pin = 12u; pin <= 19u; ++pin)
        gpio_set_function(pin, GPIO_FUNC_HSTX);
}

static void hstx_start(void) {
    hstx_init_line_buffers();
    hstx_active_frame = __atomic_load_n(&displayed_frame, __ATOMIC_ACQUIRE);
    hstx_next_line = 0;
    for (uint index = 0; index < 2u; ++index) {
        dma_channel_config c = dma_channel_get_default_config(hstx_dma[index]);
        channel_config_set_chain_to(&c, hstx_dma[index ^ 1u]);
        channel_config_set_dreq(&c, DREQ_HSTX);
        dma_channel_configure(hstx_dma[index], &c, &hstx_fifo_hw->fifo,
                              vblank_line, count_of(vblank_line), false);
        hstx_program_next(index); // lines 0 and 1
    }
    // The interrupt runs on this core (core 1); core 0 never sees it.
    dma_hw->ints1 = (1u << hstx_dma[0]) | (1u << hstx_dma[1]);
    dma_hw->inte1 = (1u << hstx_dma[0]) | (1u << hstx_dma[1]);
    irq_set_exclusive_handler(DMA_IRQ_1, hstx_dma_irq);
    irq_set_enabled(DMA_IRQ_1, true);
    hstx_configure();
    dma_channel_start(hstx_dma[0]);
}

static void dvi_core1(void) {
    // Notify core 0 that runtime_run_per_core_initializers() has completed.
    multicore_fifo_push_blocking(0u);
    // Wait until core 0 has filled the frames with the boot pattern.
    multicore_fifo_pop_blocking();
    hstx_start();
    multicore_fifo_push_blocking(0u);
    for (;;)
        __wfi();
}

void dvi_display_init(void) {
    source_frames[0] = sram_frames[0];
    source_frames[1] = sram_frames[1];
    source_frame_has_emulator[0] = false;
    source_frame_has_emulator[1] = false;
    displayed_frame = 0;
    pending_frame = -1;

    // Two bits leave per clk_hstx cycle, so clk_hstx = bit rate / 2
    // (126 MHz NTSC, 135 MHz PAL); the HSTX divider is 1..3.
    const uint32_t sys_hz = clock_get_hz(clk_sys);
    const uint32_t hstx_hz = MODE_BIT_CLK_KHZ * 500u;
    if (sys_hz != hstx_hz * 2u ||
        !clock_configure(clk_hstx, 0,
                         CLOCKS_CLK_HSTX_CTRL_AUXSRC_VALUE_CLK_SYS,
                         sys_hz, hstx_hz))
        panic("HSTX clock does not match the DVI mode");
    // The SDK's runtime init leaves HSTX in reset; release it once its
    // clock runs, before core 1 configures it.
    reset_unreset_block_num_wait_blocking(RESET_HSTX);
    hstx_dma[0] = (uint)dma_claim_unused_channel(true);
    hstx_dma[1] = (uint)dma_claim_unused_channel(true);
    multicore_launch_core1(dvi_core1);
}

static void dvi_fill_boot_pattern(uint8_t *frame) {
    static const uint8_t bars[8] = {
        0xe0, // red
        0xfc, // yellow
        0x1c, // green
        0x1f, // cyan
        0x03, // blue
        0xe3, // magenta
        0xff, // white
        0x00, // black
    };

    for (uint y = 0; y < DVI_FRAME_H; ++y) {
        for (uint x = 0; x < DVI_FRAME_W; ++x) {
            uint8_t pixel = bars[(x * count_of(bars)) / DVI_FRAME_W];
            // White frame makes cropping and vertical stability obvious.
            if (x < 4u || x >= DVI_FRAME_W - 4u ||
                y < 4u || y >= DVI_FRAME_H - 4u)
                pixel = 0xffu;
            frame[y * DVI_FRAME_W + x] = pixel;
        }
    }
}

void dvi_display_start(void) {
    dvi_fill_boot_pattern(source_frames[0]);
    dvi_fill_boot_pattern(source_frames[1]);
    boot_pattern_until_us = time_us_64() + 1500000u;

    // Frame presentation performs large PSRAM writes on core 0. Give scanout
    // and its DMA channels priority so those writes cannot starve it.
    hw_set_bits(&busctrl_hw->priority,
                BUSCTRL_BUS_PRIORITY_PROC1_BITS |
                BUSCTRL_BUS_PRIORITY_DMA_R_BITS |
                BUSCTRL_BUS_PRIORITY_DMA_W_BITS);
    hw_clear_bits(&busctrl_hw->priority, BUSCTRL_BUS_PRIORITY_PROC0_BITS);
    while (!busctrl_hw->priority_ack)
        tight_loop_contents();

    multicore_fifo_push_blocking(0u);
    multicore_fifo_pop_blocking();
    printf("DVI: HSTX %s emulator scanout on %s\n",
           DVI_MODE_NAME, BOARD_DVI_PIN_RANGE);
}
