# Pick the 68000 opcode handlers to run from SRAM (omega/m68khot.h) from
# PC samples taken on the board.
#
#   hotops.py sample <elf> <seconds> <counts.json>
#       Sample core 0 (non-halting, like profile.py) for about <seconds>
#       while the board runs the software of interest, and add the handler
#       shares of this session to counts.json (created if missing).
#   hotops.py header <counts.json> [count] [out]
#       Write the `count` (default 100) handlers with the highest share,
#       each session weighted equally, to `out` (default omega/m68khot.h).
#
# Handler names do not depend on where the handlers live, so any build can
# be sampled. Sample each workload as its own session (e.g. Workbench boot,
# a game) so a long session does not outweigh the others.
import bisect, json, os, re, subprocess, sys, time
from collections import Counter

HEADER = '''/* Hottest 68000 opcode handlers, placed in SRAM (.time_critical.*) so
   they do not compete with Kickstart and chip RAM for the XIP cache; the
   other handlers stay in flash. Generated by tooling/hotops.py from PC
   samples on the board ({sessions}). Included from m68kops.h after the
   handler prototypes when OMEGA_HOT_OPCODES_IN_RAM is on. */
#ifndef M68KHOT__HEADER
#define M68KHOT__HEADER
#include "pico.h"

{decls}

#endif /* M68KHOT__HEADER */
'''


def symbols(elf):
    syms = []
    out = subprocess.run(['arm-none-eabi-nm', '-n', '-S', '--defined-only', elf],
                         capture_output=True, text=True).stdout
    for line in out.splitlines():
        p = line.split()
        if len(p) == 4 and p[2] in 'tTwW':
            syms.append((int(p[0], 16), int(p[1], 16), p[3]))
    syms.sort()
    return syms


def sample(elf, seconds, path):
    syms = symbols(elf)
    starts = [s[0] for s in syms]

    def name(pc):
        i = bisect.bisect_right(starts, pc) - 1
        if i >= 0 and pc < syms[i][0] + max(syms[i][1], 2):
            return syms[i][2]
        return '?'

    oc = ['openocd', '-s', '/usr/share/openocd/scripts', '-f',
          'interface/cmsis-dap.cfg', '-f', 'target/rp2350.cfg']
    pcs = []
    end = time.time() + seconds
    while time.time() < end:
        cmds = ['-c', 'adapter speed 20000', '-c', 'init']
        for _ in range(1500):
            cmds += ['-c', 'echo p:[capture {mdw 0xe000101c 1}]']
        out = subprocess.run(oc + cmds + ['-c', 'exit'],
                             capture_output=True, text=True).stderr
        pcs += [int(m, 16) & ~1 for m in
                re.findall(r'^p:0x[0-9a-f]+: ([0-9a-f]+)', out, re.M)]
        time.sleep(0.25)  # spread the samples over the session
    counts = Counter(n for n in map(name, pcs) if n.startswith('m68k_op_'))
    data = json.load(open(path)) if os.path.exists(path) else []
    data.append({'samples': len(pcs),
                 'shares': {k: v / len(pcs) for k, v in counts.items()}})
    json.dump(data, open(path, 'w'), indent=0)
    print(f'{len(pcs)} samples, {sum(counts.values())} in {len(counts)} '
          f'handlers; {len(data)} sessions in {path}')


def header(path, count, out):
    data = json.load(open(path))
    total = Counter()
    for session in data:
        for k, v in session['shares'].items():
            total[k] += v / len(data)
    hot = sorted(k for k, _ in total.most_common(count))
    decls = '\n'.join(f'void __not_in_flash_func({k})(void);' for k in hot)
    open(out, 'w').write(HEADER.format(
        sessions=f'{len(data)} sessions', decls=decls))
    print(f'wrote {len(hot)} handlers to {out}')


if __name__ == '__main__':
    if len(sys.argv) >= 5 and sys.argv[1] == 'sample':
        sample(sys.argv[2], float(sys.argv[3]), sys.argv[4])
    elif len(sys.argv) >= 3 and sys.argv[1] == 'header':
        here = os.path.dirname(os.path.abspath(__file__))
        sys.exit(header(sys.argv[2],
                        int(sys.argv[3]) if len(sys.argv) > 3 else 100,
                        sys.argv[4] if len(sys.argv) > 4 else
                        os.path.join(here, '..', 'omega', 'm68khot.h')))
    else:
        sys.exit(__doc__ or 'usage: see the comment at the top of hotops.py')
